main: net.notfab.dimensionchanger.DimensionChanger
version: 2.0
name: DimensionChanger
author: Fabricio20
api-version: 1.13
load: POSTWORLD
description: >
  DimensionChanger allows you to change the color of the sky of your worlds.
commands:
  dc:
    description: DimensionChanger